services:
  db:
    image: postgres:15    
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cardindex
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: ./
    command: uvicorn app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    env_file: 
      - ./.env
    depends_on:
      db:
        condition: service_healthy
        restart: true

volumes:
  postgres_data: