name: PyTest

on: push

jobs:
  test:
    name: Test app
    runs-on: ubuntu-latest
    services:
        postgres:
            image: postgres:15
            env:
                POSTGRES_USER: postgres
                POSTGRES_PASSWORD: postgres
                POSTGRES_DB: cardindex_test
            ports:
                - 5432:5432  
    env:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/cardindex_test"  
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Setup python
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"
        - name: Install dependencies
          run: |
            pip install poetry
            poetry config virtualenvs.create false
            poetry install
        - name: Run tests
          run: poetry run pytest      