name: PyTest

on: push

jobs:
  test:
    name: Test app
    runs-on: ubuntu-latest
    services:
        postgres:
            image: postgres:15
            env:
                POSTGRES_USER: postgres
                POSTGRES_PASSWORD: postgres
                POSTGRES_DB: cardindex_test
            ports:
                - 5432:5432  
    env:
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/cardindex_test"  
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Setup python
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"
        - name: Install dependencies
          run: |
            pip install poetry
            poetry config virtualenvs.create false
            poetry install --no-root
        - name: Run tests
          run: poetry run pytest --aluredir=allure-results
  
  generate_report:
    name: Generate report
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: "21"
      - name: Setup Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz 
          sudo tar -zxvf allure-2.23.1.tgz -C /opt/ 
          sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure
      - name: Download  
        
       
